/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010 Facebook, Inc. (http://www.facebook.com)          |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_FBML_H__
#define __EXT_FBML_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <cpp/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

bool f_fbml_tag_list_expanded_11();
void f_fbml_complex_expand_tag_list_11(CArrRef new_tags, CArrRef new_attrs, CArrRef special_html, CArrRef precache, CArrRef style, CArrRef style_attrs, CArrRef script_attrs, CArrRef rewrite_attrs, CArrRef special_attrs, CArrRef schema);
Array f_fbml_parse_opaque_11(CStrRef unsanitized_fbml, bool body_only, bool preserve_comment, bool internal_mode = false, CVarRef css_sanitizer = null_variant, CVarRef js_sanitizer = null_variant, CVarRef attr_rewriter = null_variant);
Array f_fbml_sanitize_css_11(CStrRef unsanitized_css, bool decl_only, int line_number, CArrRef css_sanitizer);
Array f_fbml_sanitize_js_11(CStrRef unsanitized_js, int line_number, CArrRef js_sanitizer);
String f_fbml_get_tag_name_11(CObjRef node);
Array f_fbml_get_children_11(CObjRef node);
int f_fbml_get_children_count_11(CObjRef node);
Array f_fbml_get_children_by_name_11(CObjRef node, CStrRef tag);
Array f_fbml_get_attributes_11(CObjRef node);
String f_fbml_get_attribute_11(CObjRef node, CStrRef name);
Variant f_fbml_attr_to_bool_11(CStrRef name);
String f_fbml_attr_to_color_11(CStrRef name);
String f_fbml_get_text_11(CObjRef node);
void f_fbml_precache_11(CObjRef node, CVarRef data, CStrRef callback);
Array f_fbml_batch_precache_11(CObjRef node);
String f_fbml_render_children_11(CObjRef node, CVarRef data, CStrRef html_callback, CStrRef fb_callback, int internal_mode = 0);
String f_fbml_flatten_11(CObjRef node);
String f_html_profile(CStrRef html);
String f_fbjsparse(CStrRef input);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_FBML_H__
